version: '3.1'

services:

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      NODE_ENV: "production"
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_HOST: "n8n.codingsrc.work"
      N8N_PROTOCOL: "https"
      N8N_PORT: "443"
      VUE_APP_URL_BASE_API: "https://n8n.codingsrc.work/"
      GENERIC_TIMEZONE: "Europe/Berlin"
    volumes:
      - /data/n8n:/data


  # SSL Certificate
  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


  # Shared entry point for web accessible services
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    links:
      - n8n
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./data/nginx/includes/n8n.conf:/etc/nginx/conf.d/includes/n8n.conf:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
